/* Generated By:JavaCC: Do not edit this line. MathExpressionParserConstants.java */
package net.hakugyokurou.fds.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface MathExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 4;
  /** RegularExpression Id. */
  int SUB = 5;
  /** RegularExpression Id. */
  int MUL = 6;
  /** RegularExpression Id. */
  int DIV = 7;
  /** RegularExpression Id. */
  int EOL = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int RATIONAL = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\n\"",
    "<INTEGER>",
    "<RATIONAL>",
    "<DIGIT>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
